name: Build master - $(Build.BuildId)

trigger:
  branches:
    include:
      - master

stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/build-docs.yml
    - template: .ci/utils/prepare-cache.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/utils/prepare-cache.yml

  - job: Windows
    pool:
      vmImage: windows-2019
    timeoutInMinutes: 120
    variables:
      CACHE_FOLDER: $(Pipeline.Workspace)/cache
    steps:
    - template: .ci/build-platform.yml
    - template: .ci/utils/prepare-cache.yml

- stage: Publish_docs
  displayName: Publish documentation
  dependsOn: [Build]
  jobs:
  - deployment: Publish_docs
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish docs to GitHub
    environment: gh-pages
    pool:
      vmImage: ubuntu-16.04
    strategy:
      runOnce:
        deploy:
          steps:
            - template: .ci/publish-api-docs.yml

